export const ROUTES = {
  HOME: '/',
  FOR_PET_OWNERS: '/for-pet-owners',
  FOR_VETS: '/for-vets',
  QUESTIONNAIRE: '/questionnaire',
  NEWS: '/news',
  ABOUT: '/about',
  PRIVACY: '/privacy',
  IMPRESS: '/impress',
  CONTACT: '/contact',
  CUSTOMERS: '/customers',
  USERS: '/users',
  QUESTIONNAIRES: '/questionnaires',
  PAGE_HOME: '/webcontent/page/home',
  PAGE_NEWS: '/webcontent/page/news',
  PAGE_ABOUT: '/webcontent/page/about',
  PAGE_PRIVACY: '/webcontent/page/privacy',
  PAGE_IMPRINT: '/webcontent/page/imprint',
  PAGE_CONTACT: '/webcontent/page/contact',
  IMAGES: '/webcontent/images',
  TAGS: '/webcontent/tags',
} as const;
